### ISSUE TITLE
Bring Metric data to Splunk Indexer Cluster directly without any Load Balancer Address.

### ISSUE THREAD

**Issue by rafeeqsid** [guilhemmarchand/TA-influxdata-telegraf#1]
I want to bring Metric data from host to Splunk Indexer Cluster without using in between Load Balancer. So no of the solution like via HEC and LB address of Indexer Cluster.

Via HEC bringing data from 10K+ will create a bottleneck at HEC Cluster.
Via LB:- We don't want to change the Existing solution just like to map the Indexer Cluster with LB Address.

Let me know if this is possible to do this.

**Comment by guilhemmarchand** [comment]
@rafeeqsid 

Right, there are indeed different options available if you do not want to rely on HEC for the forwarding of the metrics to Splunk.
However, note that HEC is an highly scalable and evolutive way for high scale data volume, so you may want to consider this properly.

Do you have the Splunk UF deployed across these hosts?

**Comment by rafeeqsid** [comment]
Yes UF Deployed across all these host(10k+ for Linux and 5K+ for Windows) .Just wanted to know that how we can push the metrics data via UF to Indexer cluster without having any LB in between.

**Comment by guilhemmarchand** [comment]
@rafeeqsid 

There woud be at leas 3 options to have Splunk UF ingesting the metrics and transporting the data to your indexers via S2S (Splunk transport via the UF):

**Some links:**

- https://telegraf-os.readthedocs.io/en/latest/telegraf.html
- https://www.splunk.com/en_us/blog/it/the-daily-telegraf-getting-started-with-telegraf-and-splunk.html

**In short you could:**

1.  Use the telegraf file output mode (splunkmetric mode like in the second link) and have the UF monitoring the log file
2. Use the telegraf tcp output mode (either graphite with additional parsing on the Splunk side, or potentially splunkmetric mode directly should work too) sending to 127.0.0.1 and have the UF running a tcp input mode locally (So telegraf sends to the tcp input on the loopback)
3. Run telegraf in standard output mode via an input script ran by the UF and ingesting its content (less preferable IMO)

For 1 you will need to handle cleaning the file. (using rotate.d or a custom script to avoid letting the file growing over time)
2 could be a good design too as long as you allow running a listener locally

**Comment by rafeeqsid** [comment]
I took option 1 for this and getting following error "Metric name is missing for source=/tmp/metrics.out,sourcetype=telegraf"

Below are my configuration:-
output stanza:-
[[outputs.file]]
 files = ["/tmp/metrics.out"]
 data_format = "splunkmetric"

props.conf stanza for Splunk Indexer:-
[telegraf]
category = Metrics
description = Telegraf Metrics
pulldown_type = 1
DATETIME_CONFIG =
NO_BINARY_CHECK = true
SHOULD_LINEMERGE = true
disabled = false
INDEXED_EXTRACTIONS = json
KV_MODE = none
TIMESTAMP_FIELDS = time

indexs.conf on indexer
#indexes.conf

[osmetric_test]
homePath = $SPLUNK_DB/osmetric_test/db
coldPath = $SPLUNK_DB/osmetric_test/colddb
thawedPath = $SPLUNK_DB/osmetric_test/thaweddb
datatype = metric
maxTotalDataSizeMB = 512000

inputs.conf stanza:-
[monitor:///tmp/metrics.out]
index = osmetric_test
sourcetype = telegraf

**Comment by guilhemmarchand** [comment]
Hi @rafeeqsid 

Right ok, but are you getting metrics ingested properly or not at all?

--> Use mstats / mcatalog / msearch / mpreview to verify if you get metrics for these hosts

I could think about a few options, like:

- You get metrics but some "measures" are not compliant with Splunk metric format (like non numerical) and Splunk complains
- You have a misconfiguration, like missing Splunk indexing config on the right layer like heavy forwarders acting as intermediate

That json based configuration I haven't tested it personally, the one I used to use and provided before telegraf was able to send straight to HEC uses the graphite output fornat:

https://telegraf-os.readthedocs.io/en/latest/telegraf.html#splunk-file-monitoring-ingestion

The graphite output format relies on the following props from the TA:

```
[file:telegraf:graphite]
LINE_BREAKER = ([\n\r]+)
TRUNCATE = 0
TIME_PREFIX = [^\s]*\s[^\s]*\s
TIME_FORMAT =  %s
NO_BINARY_CHECK = true
SHOULD_LINEMERGE = false
pulldown_type = 1
TRANSFORMS-file_telegraf_graphite = telegraf_graphite_host, telegraf_graphite_metric_name, telegraf_graphite_metric_dimension, telegraf_graphite_metric_value
category = Metrics

```

This defitively works, the json should work too but maybe there are bad measures?
An easy to verify is to send the data to a non metric index for verification purposes, then use normal event searches to find the anomalies

**Comment by rafeeqsid** [comment]
Right ok, but are you getting metrics ingested properly or not at all?

--> Use mstats / mcatalog / msearch / mpreview to verify if you get metrics for these hosts  **_Yes verified but no metric data comming in._**

I could think about a few options, like:

You get metrics but some "measures" are not compliant with Splunk metric format (like non numerical) and Splunk complains
You have a misconfiguration, like missing Splunk indexing config on the right layer like heavy forwarders acting as intermediate 
**There is no Heavy forwarder which acting as Intermediate, It goes from Universal Forwarder to Indexer.**

**Comment by guilhemmarchand** [comment]
Ok, I'll give a test to that configuration mentioned on the Splunk blog page, it should work so there must be a reason.
In the meantime you can use the graphite output format for your testing purposes.

**Comment by rafeeqsid** [comment]
I made the below changes in props.conf and routed the data to new source type but this time did not get previous error and no data in splunk.

[file:telegraf:graphite]
LINE_BREAKER = ([\n\r]+)
TRUNCATE = 0
TIME_PREFIX = [^\s]*\s[^\s]*\s
TIME_FORMAT =  %s
NO_BINARY_CHECK = true
SHOULD_LINEMERGE = false
pulldown_type = 1
TRANSFORMS-file_telegraf_graphite = telegraf_graphite_host, telegraf_graphite_metric_name, telegraf_graphite_metric_dimension, telegraf_graphite_metric_value
category = Metrics

**Comment by guilhemmarchand** [comment]
Have you updated the telegraf.conf like explained in the Docs?

**Comment by rafeeqsid** [comment]
> Have you updated the telegraf.conf like explained in the Docs?

Yes

**Comment by guilhemmarchand** [comment]
@rafeeqsid 

I can confirm that this configuration was fully working when it was designed, I doubt anything changed on this side, so this should be working fine.

I would advise you to try ingesting into the testing event index to check that the data is first going trhough, and then what its format is.

**Comment by guilhemmarchand** [comment]
I will verify this is working very shortly

**Comment by guilhemmarchand** [comment]
@rafeeqsid 

So I just gave it a shoot and to me it is fully working as expected.

- I deployed the TA on the indexing layer
- On a Linux box, I installed telegraf with the following output:

```
[[outputs.file]]
  ## Files to write to, "stdout" is a specially handled file.
  files = ["/tmp/metrics.out"]

  ## Data format to output.
  ## Each data format has its own unique set of configuration options, read
  ## more about them here:
  ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_OUTPUT.md
  data_format = "graphite"
  graphite_tag_support = true

```

On the Splunk UF I created a simplistic inputs.conf:

```
root@vagrantvm:~# cat /opt/splunkforwarder/etc/system/local/inputs.conf
[monitor:///tmp/metrics.out]
disabled = false
index = telegraf_testfile
sourcetype = file:telegraf:graphite

```


"telegraf_testfile" is a metric index I just created, after the Splunk UF, I can see the metrics perfectly coming in:

![image](https://user-images.githubusercontent.com/7503059/99528860-cf055b00-2996-11eb-8f98-31e8abeb8867.png)

![image](https://user-images.githubusercontent.com/7503059/99529228-5eab0980-2997-11eb-9533-0cb3026af978.png)


I suggest you review carefully step by step your configuration and just follow this / the doc

Let me know ;-)

**Comment by rafeeqsid** [comment]
Yes, Its work for me but additionall challenge is to manage the log rotation remotely for /tmp/metrics.out. But switching to explore option 2, That how loopback address will send data to Splunk..

Below option was shared by you:-
Use the telegraf tcp output mode (either graphite with additional parsing on the Splunk side, or potentially splunkmetric mode directly should work too) sending to 127.0.0.1 and have the UF running a tcp input mode locally (So telegraf sends to the tcp input on the loopback)

Just need some configuration for tcp output mode and which source type will used for this.

Environment:-
UF sending data to IDX directly without LB in between.

Thankyou in advance

**Comment by guilhemmarchand** [comment]
@rafeeqsid 

Yes with local file you need to define where to write (/tmp/metrics.out is just provided as for an example and in real life you would potentially want to write somewhere else) and you need to handle the file rotation.
Linux has rotate.d which is pretty easy and could handle the task for you. 

To reply to your question:

https://telegraf-os.readthedocs.io/en/latest/telegraf.html#tcp-tcp-ssl-inputs

**This would mean:**

- Create a TA app that you deploy to the UF using the Splunk deployment server
- In this app have a local/inputs.conf (or default/inputs.conf) which a TCP input listener, like

```
[tcp://2003]
connection_host = dns
index = telegraf
sourcetype = tcp:telegraf:graphite
acceptFrom = 127.0.0.1
```

Once the app is deployed, the UF should start a tcp listener which is accepting connections from the loopback only.

- In telegraf you would have:

```
[[outputs.graphite]]
  ## TCP endpoint for your graphite instance.
  ## If multiple endpoints are configured, the output will be load balanced.
  ## Only one of the endpoints will be written to with each iteration.
  servers = ["127.0.0.1:2003"]
  ## Prefix metrics name
  prefix = ""
  ## Graphite output template
  ## see https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_OUTPUT.md
  # template = "host.tags.measurement.field"

  ## Enable Graphite tags support
  graphite_tag_support = true

  ## timeout in seconds for the write connection to graphite
  timeout = 2
```

If you deploy telegraf as a Splunk app this could be in the same app.

I haven't tested this setup specially, but it's non without sense (it is frequent for programs interracting between each others to open a local listener) and should work

**Comment by rafeeqsid** [comment]
I tried but it didn't work as telegraf service didn't start at forwarder end after pushing from Deployment Server. Only change i made for the port from 2003 to 9997(This is our Indexer Listener).

**Comment by guilhemmarchand** [comment]
@rafeeqsid 

" Only change i made for the port from 2003 to 9997(This is our Indexer Listener)."

No you didn't understand, no relation ship with that. re-read carefully what I was explaining.

loopback means local network interface, which means the endpoint (the server) runs a listener which listens locally, and telegraf sends locally to this listener, nothing to see with your indexers.

"telegraf service didn't start at forwarder end after pushing from Deployment Server"

Why? What do you mean? Did you check?

**Comment by rafeeqsid** [comment]
Below is the configuration i made
 inputs.conf
[tcp://9997]
connection_host = dns
index = telegraf
sourcetype = tcp:telegraf:graphite
acceptFrom = 127.0.0.1

telegraf.conf  
[[outputs.graphite]]
  servers = ["127.0.0.1:9997"]
  prefix = ""
  graphite_tag_support = true
  timeout = 2

**Comment by guilhemmarchand** [comment]
@rafeeqsid  Where do you deploy the inputs.conf? 
It should be on the UF side, because the UF would start the TCP input. (not the indexers)

**Comment by rafeeqsid** [comment]
I reverted the changes what you suggested earlier .Still the Telegraf service didn't start at forwarder end.

It should be on the UF side, because the UF would start the TCP input. (not the indexers) **This is at UF side.

inputs.conf
[tcp://2003]
connection_host = dns
index = telegraf
sourcetype = tcp:telegraf:graphite
acceptFrom = 127.0.0.1

telegraf.conf
[[outputs.graphite]]
servers = ["127.0.0.1:2003"]
prefix = ""
graphite_tag_support = true
timeout = 2

**Comment by guilhemmarchand** [comment]
If you are using my app example:

https://github.com/guilhemmarchand/TA-telegraf-amd64/

Then you can on the UF run it manually and check what is happening.

ex:

As the Unix owning the Splunk processes:

```
/opt/splunkforwarder/bin/splunk cmd /opt/splunk/etc/apps/TA-telegraf-amd64/bin/init.sh status
/opt/splunkforwarder/bin/splunk cmd /opt/splunk/etc/apps/TA-telegraf-amd64/bin/init.sh stop
/opt/splunkforwarder/bin/splunk cmd /opt/splunk/etc/apps/TA-telegraf-amd64/bin/init.sh start
```

You can as well run the telegraf process manually, for example:

```
/opt/splunkforwarder/etc/apps/TA-telegraf-amd64/bin/telegraf/usr/bin/telegraf -config /opt/splunk/etc/apps/TA-telegraf-amd64/local/telegraf.conf
```

Check out if the process is in machine, if it is maybe it is blocked somehow per this would be surprising, maybe it does not start because it cannot access to the TCP input?

**Comment by rafeeqsid** [comment]
No Result from below command.

/opt/splunkforwarder/bin/splunk cmd /opt/splunk/etc/apps/TA-telegraf-amd64/bin/init.sh status
/opt/splunkforwarder/bin/splunk cmd /opt/splunk/etc/apps/TA-telegraf-amd64/bin/init.sh stop
/opt/splunkforwarder/bin/splunk cmd /opt/splunk/etc/apps/TA-telegraf-amd64/bin/init.sh start
/opt/splunkforwarder/etc/apps/TA-telegraf-amd64/bin/telegraf/usr/bin/telegraf -config /opt/splunk/etc/apps/TA-telegraf-amd64/local/telegraf.conf

with Loopback Listening, telegraf is not working. Let me know if there is some workaround on this .

**Comment by guilhemmarchand** [comment]
I'll give it a shot and will let know.
It's not possile the commands didn't give any output at all

**Comment by guilhemmarchand** [comment]
@rafeeqsid 

So I gave a shoot, and it is working perfectly fine ;-)
I think you misinterpreted my instructions, so let me be more clear.

**I took my app example which is deployed via the Splunk Deployment Server:**

https://github.com/guilhemmarchand/TA-telegraf-amd64

In the file:

TA-telegraf-amd64/local/inputs.conf

I added the TCP local listener, such that you have:

```
# inputs.conf

# start telegraf at Splunk start, and restart if Splunk is restarted. (which allows upgrading easily Telegraf binaries shipped with the TA package)
[script://./bin/init.sh restart]
disabled = false
interval = -1

# local TCP listener
[tcp://2003]
connection_host = dns
index = telegraf
sourcetype = tcp:telegraf:graphite
acceptFrom = 127.0.0.1
```

Then I edited the file:

TA-telegraf-amd64/local/telegraf.conf

To configure (add) the outputs for graphite TCP (I am wondering if you did empty the file?)

You need to have:

```
[[outputs.graphite]]
 servers = ["127.0.0.1:2003"]
 prefix = ""
 graphite_tag_support = true
 timeout = 2
```

If I remove all commented lines, the full telegraf.conf is:

```
[global_tags]
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  logfile = ""
  hostname = ""
  omit_hostname = false
[[outputs.graphite]]
 servers = ["127.0.0.1:2003"]
 prefix = ""
 graphite_tag_support = true
 timeout = 2
[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false
[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "overlay", "aufs", "squashfs"]
[[inputs.diskio]]
[[inputs.kernel]]
[[inputs.mem]]
[[inputs.processes]]
[[inputs.swap]]
[[inputs.system]]
 [[inputs.net]]
 [[inputs.netstat]]
 [[inputs.procstat]]
    pattern = ".*"
```

Once re-redeployed, the telegraf starts and boom metrics ;-)

To handle the telegraf process manually, you can do:

```
root@vagrantvm:~# /opt/splunkforwarder/bin/splunk cmd /opt/splunkforwarder/etc/apps/TA-telegraf-amd64/bin/init.sh status
telegraf Process is running [ OK ]
```

```
root@vagrantvm:~# /opt/splunkforwarder/bin/splunk cmd /opt/splunkforwarder/etc/apps/TA-telegraf-amd64/bin/init.sh stop
telegraf process was stopped [ OK ]
```

```
root@vagrantvm:~# /opt/splunkforwarder/bin/splunk cmd /opt/splunkforwarder/etc/apps/TA-telegraf-amd64/bin/init.sh start
Starting the process telegraf [ OK ]
telegraf process was started [ OK ]
```

```
root@vagrantvm:~# /opt/splunkforwarder/etc/apps/TA-telegraf-amd64/bin/telegraf/usr/bin/telegraf -config /opt/splunkforwarder/etc/apps/TA-telegraf-amd64/local/telegraf.conf
2020-11-25T21:47:42Z I! Starting Telegraf 1.10.1
2020-11-25T21:47:42Z I! Loaded inputs: disk kernel net procstat cpu diskio mem processes swap system netstat
2020-11-25T21:47:42Z I! Loaded aggregators:
2020-11-25T21:47:42Z I! Loaded processors:
2020-11-25T21:47:42Z I! Loaded outputs: graphite
2020-11-25T21:47:42Z I! Tags enabled: host=vagrantvm
2020-11-25T21:47:42Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"vagrantvm", Flush Interval:10s
```

In the end:

- The DS deploys the TA containing both the telegraf binary and the configuration
- The UF starts a TCP listener locally which only accepts connections from the local host
- Telegraf sends metrics locally to the TCP listener
- Data is transported via the Splunk S2S protocol (Splunk forwarding)
- Data is being cooked and parsed on the Splunk side and stored in the metric store

Working as I said it would.

![image](https://user-images.githubusercontent.com/7503059/100285304-918d6880-2f68-11eb-925e-fe5a7dd56a0c.png)

**pros for this method:**

- No need to handle any file rotation unlike when writting to file, no risks of filling the FS in case of an issue with the rotation
- Stream approach, no file monitoring, low impact in the UF

**cons for this method**

- If the UF is not up, not able to listen and forward, or anything impacts the UF itself, metric will not be available (while file mode, the UF would be able to restart where it stopped and backfill the metrics as long as the file still contain these)

Something important to say for these two "graphite" mode approaches, a parsing at indexing time is required to transforms these "events" into proper metrics, this work happens at the Splunk indexing level.
At very high scale, this requires compute resources on the indexers.

These events are pretty small events and the sourcetypes are very performing configs, however the HEC approach has the advantages of using an HEC endpoint (collector) which does not perform parsing at the ingestion level and does not go trhough all Splunk queues which can be impacting at very high scale (the splunkmetrics output mode formats the JSON events into a format that is expected for metrics ingested over HEC)

Plus, in latest versions of Splunk, the metric store allows indexing multiple metrics in a single operation while the graphite format means one event = one metric, potentially there is a superior cost in licensing in the end due to the way the metrics licensing costs are being calculated.

I would recommend you to reconsider the approach of avoiding the HEC layer, this remains my recommandation for the integration between Telegraf to Splunk.

Lastly, another solution could be to do the same thing with HEC than I did with TCP, which means running an HEC endpoint locally on the UF and having Telegraf sending to the local HEC endpoint, in theory Splunk does not support yet running HEC on a UF, in true what is not supported is the raw HEC endpoint parsing which is not used by Telegraf when streaming metrics to HEC, so most likely this would too, data would remain transported via S2S but the format and the ingestion would save you from the indexing costs potentially.

**Comment by guilhemmarchand** [comment]
**This I would recommend instead of TCP and Graphite:**

(same philosophy, but uses HEC instead of TCP)

TA-telegraf-amd64/local/inputs.conf

```
# inputs.conf

# start telegraf at Splunk start, and restart if Splunk is restarted. (which allows upgrading easily Telegraf binaries shipped with the TA package)
[script://./bin/init.sh restart]
disabled = false
interval = -1

# local HEC listener
[http]
disabled = 0
acceptFrom = 127.0.0.1

[http://telegraf]
disabled = 0
index = telegraf
indexes = telegraf
token = c53db41e-c8e8-11ea-a8a7-acde48001122
```

TA-telegraf-amd64/local/telegraf.conf

```
[global_tags]
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  logfile = ""
  hostname = ""
  omit_hostname = false
[[outputs.http]]
   url = "https://127.0.0.1:8088/services/collector"
   timeout = "5s"
   insecure_skip_verify = true
   data_format = "splunkmetric"
   splunkmetric_hec_routing = true
    [outputs.http.headers]
      Content-Type = "application/json"
      Authorization = "Splunk c53db41e-c8e8-11ea-a8a7-acde48001122"
      X-Splunk-Request-Channel = "c53db41e-c8e8-11ea-a8a7-acde48001122"
[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false
[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "overlay", "aufs", "squashfs"]
[[inputs.diskio]]
[[inputs.kernel]]
[[inputs.mem]]
[[inputs.processes]]
[[inputs.swap]]
[[inputs.system]]
 [[inputs.net]]
 [[inputs.netstat]]
 [[inputs.procstat]]
    pattern = ".*"
```

**Just verified, and works perfectly fine.**

This is superior to the non splunkmetrics mode from a technical, cost and performance point of view.

Note: Given that connecttivity is local only, you could even get rid of SSL and run HEC in non SSL.

**Comment by rafeeqsid** [comment]
Issue got fixed there were issue in script which was not set for execution after  unzipping the TA. After changing it to executable it works, Below file was changed.

chmod 755 /opt/splunkforwarder/etc/apps/TA-telegraf-amd64/bin/telegraf/usr/bin/telegraf
chmod 755 /opt/splunkforwarder/etc/apps/TA-telegraf-amd64/bin/init.sh.
